[2021-05-16 21:23:17,490] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_rugby_pass_match_data 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-16 21:23:17,494] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_rugby_pass_match_data 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-16 21:23:17,494] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 21:23:17,494] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-05-16 21:23:17,494] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 21:23:17,499] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): get_rugby_pass_match_data> on 2021-04-24T10:00:00+00:00
[2021-05-16 21:23:17,501] {standard_task_runner.py:52} INFO - Started process 67868 to run task
[2021-05-16 21:23:17,506] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matches_links', 'get_rugby_pass_match_data', '2021-04-24T10:00:00+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matches_links/matches_links.py', '--cfg-path', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpwqikmd_q', '--error-file', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmp3mj8zhvc']
[2021-05-16 21:23:17,507] {standard_task_runner.py:77} INFO - Job 5: Subtask get_rugby_pass_match_data
[2021-05-16 21:23:17,535] {logging_mixin.py:104} INFO - Running <TaskInstance: matches_links.get_rugby_pass_match_data 2021-04-24T10:00:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2021-05-16 21:23:17,558] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=matches_links
AIRFLOW_CTX_TASK_ID=get_rugby_pass_match_data
AIRFLOW_CTX_EXECUTION_DATE=2021-04-24T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-04-24T10:00:00+00:00
[2021-05-16 21:23:17,558] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T
[2021-05-16 21:23:17,559] {bash.py:158} INFO - Running command: Rscript airflow/dags/matches_links/create_matches_table.R
[2021-05-16 21:23:17,568] {bash.py:169} INFO - Output:
[2021-05-16 21:23:17,598] {bash.py:173} INFO - Fatal error: cannot open file 'airflow/dags/matches_links/create_matches_table.R': No such file or directory
[2021-05-16 21:23:17,600] {bash.py:177} INFO - Command exited with return code 2
[2021-05-16 21:23:17,607] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-05-16 21:23:17,609] {taskinstance.py:1525} INFO - Marking task as UP_FOR_RETRY. dag_id=matches_links, task_id=get_rugby_pass_match_data, execution_date=20210424T100000, start_date=20210516T202317, end_date=20210516T202317
[2021-05-16 21:23:17,646] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-05-16 21:24:26,516] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_rugby_pass_match_data 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-16 21:24:26,521] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_rugby_pass_match_data 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-16 21:24:26,521] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 21:24:26,521] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-05-16 21:24:26,521] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 21:24:26,526] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): get_rugby_pass_match_data> on 2021-04-24T10:00:00+00:00
[2021-05-16 21:24:26,527] {standard_task_runner.py:52} INFO - Started process 68737 to run task
[2021-05-16 21:24:26,534] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matches_links', 'get_rugby_pass_match_data', '2021-04-24T10:00:00+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matches_links/matches_links.py', '--cfg-path', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpw9xjq4m1', '--error-file', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpexyh5q0o']
[2021-05-16 21:24:26,536] {standard_task_runner.py:77} INFO - Job 5: Subtask get_rugby_pass_match_data
[2021-05-16 21:24:26,563] {logging_mixin.py:104} INFO - Running <TaskInstance: matches_links.get_rugby_pass_match_data 2021-04-24T10:00:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2021-05-16 21:24:26,586] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=matches_links
AIRFLOW_CTX_TASK_ID=get_rugby_pass_match_data
AIRFLOW_CTX_EXECUTION_DATE=2021-04-24T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-04-24T10:00:00+00:00
[2021-05-16 21:24:26,587] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T
[2021-05-16 21:24:26,588] {bash.py:158} INFO - Running command: Rscript /Users/harry/rugby_data_project_airflow/R/scripts/create_matches_table.R
[2021-05-16 21:24:26,594] {bash.py:169} INFO - Output:
[2021-05-16 21:24:26,769] {bash.py:173} INFO - Error in file(filename, "r", encoding = encoding) :
[2021-05-16 21:24:26,770] {bash.py:173} INFO -   cannot open the connection
[2021-05-16 21:24:26,770] {bash.py:173} INFO - Calls: source -> file
[2021-05-16 21:24:26,770] {bash.py:173} INFO - In addition: Warning message:
[2021-05-16 21:24:26,771] {bash.py:173} INFO - In file(filename, "r", encoding = encoding) :
[2021-05-16 21:24:26,771] {bash.py:173} INFO -   cannot open file 'R/variables/data_variables.R': No such file or directory
[2021-05-16 21:24:26,772] {bash.py:173} INFO - Execution halted
[2021-05-16 21:24:26,781] {bash.py:177} INFO - Command exited with return code 1
[2021-05-16 21:24:26,787] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-05-16 21:24:26,789] {taskinstance.py:1525} INFO - Marking task as UP_FOR_RETRY. dag_id=matches_links, task_id=get_rugby_pass_match_data, execution_date=20210424T100000, start_date=20210516T202426, end_date=20210516T202426
[2021-05-16 21:24:26,807] {local_task_job.py:146} INFO - Task exited with return code 1
