[2021-05-17 09:13:13,464] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-17 09:13:13,469] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-17 09:13:13,469] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 09:13:13,469] {taskinstance.py:1069} INFO - Starting attempt 2 of 2
[2021-05-17 09:13:13,469] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 09:13:13,474] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): get_autumn_nations_cup_links> on 2021-04-24T10:00:00+00:00
[2021-05-17 09:13:13,477] {standard_task_runner.py:52} INFO - Started process 10756 to run task
[2021-05-17 09:13:13,482] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matches_links', 'get_autumn_nations_cup_links', '2021-04-24T10:00:00+00:00', '--job-id', '8', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matches_links/matches_links.py', '--cfg-path', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpdgq8zal1', '--error-file', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmp3zqjigxa']
[2021-05-17 09:13:13,484] {standard_task_runner.py:77} INFO - Job 8: Subtask get_autumn_nations_cup_links
[2021-05-17 09:13:13,512] {logging_mixin.py:104} INFO - Running <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2021-05-17 09:13:13,534] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=matches_links
AIRFLOW_CTX_TASK_ID=get_autumn_nations_cup_links
AIRFLOW_CTX_EXECUTION_DATE=2021-04-24T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-04-24T10:00:00+00:00
[2021-05-17 09:13:13,534] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T
[2021-05-17 09:13:13,535] {bash.py:158} INFO - Running command: Rscript /Users/harry/rugby_data_project_airflow/R/scripts/create_matches_table.R  https://www.rugbypass.com/autumn-nations-cup/matches/
[2021-05-17 09:13:13,542] {bash.py:169} INFO - Output:
[2021-05-17 09:13:14,677] {bash.py:173} INFO - ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
[2021-05-17 09:13:14,681] {bash.py:173} INFO - ✔ ggplot2 3.3.3     ✔ purrr   0.3.3
[2021-05-17 09:13:14,682] {bash.py:173} INFO - ✔ tibble  3.0.4     ✔ dplyr   1.0.2
[2021-05-17 09:13:14,682] {bash.py:173} INFO - ✔ tidyr   1.1.2     ✔ stringr 1.4.0
[2021-05-17 09:13:14,682] {bash.py:173} INFO - ✔ readr   1.3.1     ✔ forcats 0.5.0
[2021-05-17 09:13:14,756] {bash.py:173} INFO - ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
[2021-05-17 09:13:14,756] {bash.py:173} INFO - ✖ dplyr::filter() masks stats::filter()
[2021-05-17 09:13:14,756] {bash.py:173} INFO - ✖ dplyr::lag()    masks stats::lag()
[2021-05-17 09:13:14,765] {bash.py:173} INFO - 
[2021-05-17 09:13:14,766] {bash.py:173} INFO - Attaching package: ‘lubridate’
[2021-05-17 09:13:14,766] {bash.py:173} INFO - 
[2021-05-17 09:13:14,766] {bash.py:173} INFO - The following objects are masked from ‘package:base’:
[2021-05-17 09:13:14,767] {bash.py:173} INFO - 
[2021-05-17 09:13:14,767] {bash.py:173} INFO -     date, intersect, setdiff, union
[2021-05-17 09:13:14,767] {bash.py:173} INFO - 
[2021-05-17 09:13:14,769] {bash.py:173} INFO - Loading required package: xml2
[2021-05-17 09:13:14,776] {bash.py:173} INFO - 
[2021-05-17 09:13:14,776] {bash.py:173} INFO - Attaching package: ‘rvest’
[2021-05-17 09:13:14,776] {bash.py:173} INFO - 
[2021-05-17 09:13:14,777] {bash.py:173} INFO - The following object is masked from ‘package:purrr’:
[2021-05-17 09:13:14,777] {bash.py:173} INFO - 
[2021-05-17 09:13:14,777] {bash.py:173} INFO -     pluck
[2021-05-17 09:13:14,777] {bash.py:173} INFO - 
[2021-05-17 09:13:14,778] {bash.py:173} INFO - The following object is masked from ‘package:readr’:
[2021-05-17 09:13:14,778] {bash.py:173} INFO - 
[2021-05-17 09:13:14,778] {bash.py:173} INFO -     guess_encoding
[2021-05-17 09:13:14,779] {bash.py:173} INFO - 
[2021-05-17 09:13:14,784] {bash.py:173} INFO - [1] "Getting autumn_nations_cup links"
[2021-05-17 09:13:16,989] {bash.py:173} INFO - [1] "autumn_nations_cup saved"
[2021-05-17 09:13:16,989] {bash.py:173} INFO - Error: unexpected '}' in "}"
[2021-05-17 09:13:16,990] {bash.py:173} INFO - Execution halted
[2021-05-17 09:13:17,006] {bash.py:177} INFO - Command exited with return code 1
[2021-05-17 09:13:17,011] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-05-17 09:13:17,014] {taskinstance.py:1525} INFO - Marking task as FAILED. dag_id=matches_links, task_id=get_autumn_nations_cup_links, execution_date=20210424T100000, start_date=20210517T081313, end_date=20210517T081317
[2021-05-17 09:13:17,036] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-05-17 09:19:06,232] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-17 09:19:06,237] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-17 09:19:06,237] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 09:19:06,237] {taskinstance.py:1069} INFO - Starting attempt 2 of 2
[2021-05-17 09:19:06,237] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 09:19:06,243] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): get_autumn_nations_cup_links> on 2021-04-24T10:00:00+00:00
[2021-05-17 09:19:06,245] {standard_task_runner.py:52} INFO - Started process 14685 to run task
[2021-05-17 09:19:06,251] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matches_links', 'get_autumn_nations_cup_links', '2021-04-24T10:00:00+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matches_links/matches_links.py', '--cfg-path', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmprf_crl8y', '--error-file', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpafo906ei']
[2021-05-17 09:19:06,253] {standard_task_runner.py:77} INFO - Job 9: Subtask get_autumn_nations_cup_links
[2021-05-17 09:19:06,280] {logging_mixin.py:104} INFO - Running <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [running]> on host Henrys-MacBook-Pro.local
[2021-05-17 09:19:06,301] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=matches_links
AIRFLOW_CTX_TASK_ID=get_autumn_nations_cup_links
AIRFLOW_CTX_EXECUTION_DATE=2021-04-24T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-04-24T10:00:00+00:00
[2021-05-17 09:19:06,302] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T
[2021-05-17 09:19:06,303] {bash.py:158} INFO - Running command: Rscript /Users/harry/rugby_data_project_airflow/R/scripts/create_matches_table.R  https://www.rugbypass.com/autumn-nations-cup/matches/
[2021-05-17 09:19:06,309] {bash.py:169} INFO - Output:
[2021-05-17 09:19:06,566] {bash.py:173} INFO - Error in args[2] %>% dmy : could not find function "%>%"
[2021-05-17 09:19:06,567] {bash.py:173} INFO - Execution halted
[2021-05-17 09:19:06,578] {bash.py:177} INFO - Command exited with return code 1
[2021-05-17 09:19:06,584] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-05-17 09:19:06,587] {taskinstance.py:1525} INFO - Marking task as FAILED. dag_id=matches_links, task_id=get_autumn_nations_cup_links, execution_date=20210424T100000, start_date=20210517T081906, end_date=20210517T081906
[2021-05-17 09:19:06,636] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-05-17 09:26:48,327] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-17 09:26:48,334] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-17 09:26:48,334] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 09:26:48,334] {taskinstance.py:1069} INFO - Starting attempt 2 of 3
[2021-05-17 09:26:48,334] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 09:26:48,338] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): get_autumn_nations_cup_links> on 2021-04-24T10:00:00+00:00
[2021-05-17 09:26:48,340] {standard_task_runner.py:52} INFO - Started process 19919 to run task
[2021-05-17 09:26:48,346] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matches_links', 'get_autumn_nations_cup_links', '2021-04-24T10:00:00+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matches_links/matches_links.py', '--cfg-path', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmp2jiuuwcq', '--error-file', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmps5qgqh8f']
[2021-05-17 09:26:48,348] {standard_task_runner.py:77} INFO - Job 5: Subtask get_autumn_nations_cup_links
[2021-05-17 09:26:48,375] {logging_mixin.py:104} INFO - Running <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [running]> on host Henrys-MacBook-Pro.local
[2021-05-17 09:26:48,397] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=matches_links
AIRFLOW_CTX_TASK_ID=get_autumn_nations_cup_links
AIRFLOW_CTX_EXECUTION_DATE=2021-04-24T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-04-24T10:00:00+00:00
[2021-05-17 09:26:48,397] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T
[2021-05-17 09:26:48,398] {bash.py:158} INFO - Running command: Rscript /Users/harry/rugby_data_project_airflow/R/scripts/create_matches_table.R  https://www.rugbypass.com/autumn-nations-cup/matches/ 2021-04-24
[2021-05-17 09:26:48,405] {bash.py:169} INFO - Output:
[2021-05-17 09:26:49,583] {bash.py:173} INFO - ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
[2021-05-17 09:26:49,587] {bash.py:173} INFO - ✔ ggplot2 3.3.3     ✔ purrr   0.3.3
[2021-05-17 09:26:49,587] {bash.py:173} INFO - ✔ tibble  3.0.4     ✔ dplyr   1.0.2
[2021-05-17 09:26:49,588] {bash.py:173} INFO - ✔ tidyr   1.1.2     ✔ stringr 1.4.0
[2021-05-17 09:26:49,588] {bash.py:173} INFO - ✔ readr   1.3.1     ✔ forcats 0.5.0
[2021-05-17 09:26:49,666] {bash.py:173} INFO - ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
[2021-05-17 09:26:49,667] {bash.py:173} INFO - ✖ dplyr::filter() masks stats::filter()
[2021-05-17 09:26:49,668] {bash.py:173} INFO - ✖ dplyr::lag()    masks stats::lag()
[2021-05-17 09:26:49,677] {bash.py:173} INFO - 
[2021-05-17 09:26:49,677] {bash.py:173} INFO - Attaching package: ‘lubridate’
[2021-05-17 09:26:49,677] {bash.py:173} INFO - 
[2021-05-17 09:26:49,678] {bash.py:173} INFO - The following objects are masked from ‘package:base’:
[2021-05-17 09:26:49,678] {bash.py:173} INFO - 
[2021-05-17 09:26:49,678] {bash.py:173} INFO -     date, intersect, setdiff, union
[2021-05-17 09:26:49,678] {bash.py:173} INFO - 
[2021-05-17 09:26:49,680] {bash.py:173} INFO - Loading required package: xml2
[2021-05-17 09:26:49,687] {bash.py:173} INFO - 
[2021-05-17 09:26:49,687] {bash.py:173} INFO - Attaching package: ‘rvest’
[2021-05-17 09:26:49,688] {bash.py:173} INFO - 
[2021-05-17 09:26:49,688] {bash.py:173} INFO - The following object is masked from ‘package:purrr’:
[2021-05-17 09:26:49,688] {bash.py:173} INFO - 
[2021-05-17 09:26:49,689] {bash.py:173} INFO -     pluck
[2021-05-17 09:26:49,689] {bash.py:173} INFO - 
[2021-05-17 09:26:49,689] {bash.py:173} INFO - The following object is masked from ‘package:readr’:
[2021-05-17 09:26:49,689] {bash.py:173} INFO - 
[2021-05-17 09:26:49,690] {bash.py:173} INFO -     guess_encoding
[2021-05-17 09:26:49,690] {bash.py:173} INFO - 
[2021-05-17 09:26:49,691] {bash.py:173} INFO - Warning message:
[2021-05-17 09:26:49,692] {bash.py:173} INFO - All formats failed to parse. No formats found.
[2021-05-17 09:26:49,699] {bash.py:173} INFO - [1] "Getting autumn_nations_cup links"
[2021-05-17 09:26:51,992] {bash.py:173} INFO - Error: Can't combine `date` <character> and `date` <date>.
[2021-05-17 09:26:52,003] {bash.py:173} INFO - Backtrace:
[2021-05-17 09:26:52,004] {bash.py:173} INFO -      █
[2021-05-17 09:26:52,004] {bash.py:173} INFO -   1. ├─`%>%`(...)
[2021-05-17 09:26:52,005] {bash.py:173} INFO -   2. ├─readr::write_csv(., csv_file)
[2021-05-17 09:26:52,005] {bash.py:173} INFO -   3. │ └─readr::write_delim(...)
[2021-05-17 09:26:52,005] {bash.py:173} INFO -   4. │   ├─base::stopifnot(is.data.frame(x))
[2021-05-17 09:26:52,006] {bash.py:173} INFO -   5. │   └─base::is.data.frame(x)
[2021-05-17 09:26:52,006] {bash.py:173} INFO -   6. ├─dplyr::distinct(., rugby_pass_url, .keep_all = TRUE)
[2021-05-17 09:26:52,006] {bash.py:173} INFO -   7. └─dplyr::bind_rows(., table)
[2021-05-17 09:26:52,007] {bash.py:173} INFO -   8.   └─vctrs::vec_rbind(!!!dots, .names_to = .id)
[2021-05-17 09:26:52,007] {bash.py:173} INFO -   9.     └─(function () ...
[2021-05-17 09:26:52,007] {bash.py:173} INFO -  10.       └─vctrs::vec_default_ptype2(...)
[2021-05-17 09:26:52,008] {bash.py:173} INFO -  11.         └─vctrs:::vec_ptype2_df_fallback(x, y, opts)
[2021-05-17 09:26:52,008] {bash.py:173} INFO -  12.           └─vctrs:::vec_ptype2_params(...)
[2021-05-17 09:26:52,009] {bash.py:173} INFO -  13.             └─vctrs:::vec_ptype2_opts(x, y, opts = opts, x_arg = x_arg, y_arg = y_arg)
[2021-05-17 09:26:52,009] {bash.py:173} INFO -  14.               └─(function () ...
[2021-05-17 09:26:52,009] {bash.py:173} INFO -  15.                 └─vctrs::vec_default_ptype2(...)
[2021-05-17 09:26:52,010] {bash.py:173} INFO -  16.                   └─vctrs::stop_incompatible_type(...)
[2021-05-17 09:26:52,010] {bash.py:173} INFO -  17.                     └─vctrs:::stop_incompatible(...)
[2021-05-17 09:26:52,010] {bash.py:173} INFO -  18.                       └─vctrs:::stop_vctrs(...)
[2021-05-17 09:26:52,011] {bash.py:173} INFO - Execution halted
[2021-05-17 09:26:52,024] {bash.py:177} INFO - Command exited with return code 1
[2021-05-17 09:26:52,030] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-05-17 09:26:52,033] {taskinstance.py:1525} INFO - Marking task as UP_FOR_RETRY. dag_id=matches_links, task_id=get_autumn_nations_cup_links, execution_date=20210424T100000, start_date=20210517T082648, end_date=20210517T082652
[2021-05-17 09:26:52,078] {local_task_job.py:146} INFO - Task exited with return code 1
