[2021-05-17 09:32:48,392] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-17 09:32:48,397] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-17 09:32:48,397] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 09:32:48,397] {taskinstance.py:1069} INFO - Starting attempt 8 of 8
[2021-05-17 09:32:48,397] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 09:32:48,402] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): get_autumn_nations_cup_links> on 2021-04-24T10:00:00+00:00
[2021-05-17 09:32:48,404] {standard_task_runner.py:52} INFO - Started process 25159 to run task
[2021-05-17 09:32:48,410] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matches_links', 'get_autumn_nations_cup_links', '2021-04-24T10:00:00+00:00', '--job-id', '14', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matches_links/matches_links.py', '--cfg-path', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpjumo4_7t', '--error-file', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpkrfmltbm']
[2021-05-17 09:32:48,413] {standard_task_runner.py:77} INFO - Job 14: Subtask get_autumn_nations_cup_links
[2021-05-17 09:32:48,442] {logging_mixin.py:104} INFO - Running <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [running]> on host Henrys-MacBook-Pro.local
[2021-05-17 09:32:48,465] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=matches_links
AIRFLOW_CTX_TASK_ID=get_autumn_nations_cup_links
AIRFLOW_CTX_EXECUTION_DATE=2021-04-24T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-04-24T10:00:00+00:00
[2021-05-17 09:32:48,465] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T
[2021-05-17 09:32:48,466] {bash.py:158} INFO - Running command: Rscript /Users/harry/rugby_data_project_airflow/R/scripts/create_matches_table.R  https://www.rugbypass.com/autumn-nations-cup/matches/ 2021-04-24
[2021-05-17 09:32:48,474] {bash.py:169} INFO - Output:
[2021-05-17 09:32:48,857] {bash.py:173} INFO - 
[2021-05-17 09:32:48,858] {bash.py:173} INFO - Attaching package: ‘lubridate’
[2021-05-17 09:32:48,858] {bash.py:173} INFO - 
[2021-05-17 09:32:48,859] {bash.py:173} INFO - The following objects are masked from ‘package:base’:
[2021-05-17 09:32:48,859] {bash.py:173} INFO - 
[2021-05-17 09:32:48,859] {bash.py:173} INFO -     date, intersect, setdiff, union
[2021-05-17 09:32:48,860] {bash.py:173} INFO - 
[2021-05-17 09:32:48,860] {bash.py:173} INFO - Error in exc_date %>% dmy() : could not find function "%>%"
[2021-05-17 09:32:48,860] {bash.py:173} INFO - Execution halted
[2021-05-17 09:32:48,877] {bash.py:177} INFO - Command exited with return code 1
[2021-05-17 09:32:48,883] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-05-17 09:32:48,902] {taskinstance.py:1525} INFO - Marking task as FAILED. dag_id=matches_links, task_id=get_autumn_nations_cup_links, execution_date=20210424T100000, start_date=20210517T083248, end_date=20210517T083248
[2021-05-17 09:32:48,928] {local_task_job.py:146} INFO - Task exited with return code 1
