[2021-05-15 18:59:40,240] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: airflow_tutorial_v01.sleep 2017-06-18T09:00:00+00:00 [queued]>
[2021-05-15 18:59:40,245] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: airflow_tutorial_v01.sleep 2017-06-18T09:00:00+00:00 [queued]>
[2021-05-15 18:59:40,245] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-15 18:59:40,245] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-05-15 18:59:40,246] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-15 18:59:40,250] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): sleep> on 2017-06-18T09:00:00+00:00
[2021-05-15 18:59:40,252] {standard_task_runner.py:52} INFO - Started process 56375 to run task
[2021-05-15 18:59:40,258] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'airflow_tutorial_v01', 'sleep', '2017-06-18T09:00:00+00:00', '--job-id', '1260', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Untitled.py', '--cfg-path', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpb9b6d192', '--error-file', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpfquiy420']
[2021-05-15 18:59:40,259] {standard_task_runner.py:77} INFO - Job 1260: Subtask sleep
[2021-05-15 18:59:40,288] {logging_mixin.py:104} INFO - Running <TaskInstance: airflow_tutorial_v01.sleep 2017-06-18T09:00:00+00:00 [running]> on host henrys-macbook-pro.local
[2021-05-15 18:59:40,309] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=airflow_tutorial_v01
AIRFLOW_CTX_TASK_ID=sleep
AIRFLOW_CTX_EXECUTION_DATE=2017-06-18T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2017-06-18T09:00:00+00:00
[2021-05-15 18:59:40,310] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T
[2021-05-15 18:59:40,310] {bash.py:158} INFO - Running command: sleep 5
[2021-05-15 18:59:40,316] {bash.py:169} INFO - Output:
[2021-05-15 18:59:45,315] {local_task_job.py:174} WARNING - The recorded hostname henrys-macbook-pro.local does not match this instance's hostname 1.0.0.127.in-addr.arpa
[2021-05-15 18:59:45,323] {bash.py:177} INFO - Command exited with return code 0
[2021-05-15 18:59:45,324] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 56375
[2021-05-15 18:59:45,324] {taskinstance.py:1265} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-05-15 18:59:45,324] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2021-05-15 18:59:45,325] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
  File "/Users/harry/opt/anaconda3/lib/python3.8/tempfile.py", line 828, in __exit__
    self.cleanup()
  File "/Users/harry/opt/anaconda3/lib/python3.8/tempfile.py", line 832, in cleanup
    self._rmtree(self.name)
  File "/Users/harry/opt/anaconda3/lib/python3.8/tempfile.py", line 814, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "/Users/harry/opt/anaconda3/lib/python3.8/shutil.py", line 679, in rmtree
    def rmtree(path, ignore_errors=False, onerror=None):
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1266, in signal_handler
    task_copy.on_kill()
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/operators/bash.py", line 187, in on_kill
    os.killpg(os.getpgid(self.sub_process.pid), signal.SIGTERM)
ProcessLookupError: [Errno 3] No such process
[2021-05-15 18:59:45,335] {taskinstance.py:1525} INFO - Marking task as UP_FOR_RETRY. dag_id=airflow_tutorial_v01, task_id=sleep, execution_date=20170618T090000, start_date=20210515T175940, end_date=20210515T175945
[2021-05-15 18:59:45,353] {process_utils.py:66} INFO - Process psutil.Process(pid=56375, status='terminated', exitcode=1, started='18:59:40') (56375) terminated with exit code 1
